### ISSUE TITLE
Cleanup once NIO adopts Sendable

### ISSUE THREAD

**Issue by FranzBusch** [apple/swift-nio-ssh#110]
Once NIO adopts `Sendable` conformances we should cleanup the following things:

- [x] Remove `@preconcurrency` from imports
- [ ] Remove `@unchecked` from `SSHChildChannel` conformance

**Comment by natikgadzhi** [comment]
Hi there! Just looking for a good way to learn. Okay if I take this one?

**Comment by dnadoba** [comment]
Hi @natikgadzhi, thanks for taking a look. We have completed `Sendable` adoption but forgot to close this issue.
I don't think it's really possible for `SSHChildChannel` to remove the `@unchecked` from the `Sendable` conformance nor is it a goal. If you find anything that you think should be `Sendable` or shouldn't be `Sendable` please feel free to open an issue or PR.

**Comment by natikgadzhi** [comment]
Thank you for replying quickly! 👏
