### ISSUE TITLE
iOS: upload file to sshd server

### ISSUE THREAD

**Issue by alexe100** [apple/swift-nio-ssh#141]
Hi
I am looking from a way to upload file from my iOS app to an external ssh server.
I have tried swift-nio-ssh (NIOSSHClient example) from macos (not yet in iOS app) and I can connet to server and execute commands such as ls. Then I tried the put command and got "bash: put: command not found"... I think even though I can solve this on macos probably iOS will not have the put command. Well, my question is:
Is it possibel to use swift-nio-ssh, from an iOS app to upload a file to a ssh server not using bash commands but using class methods, such as childChannel.xx.yy.uploadfile("./abc.txt")? 

Thank you very much
Alex

**Comment by Lukasa** [comment]
swift-nio-ssh is an extremely low-level library. Its focus is on enabling the use of SSH as a protocol, not so much on making it easy to use or abstracting away mechanisms by which the high level SSH tools work. It's basically intended as a building block for a higher level library. You could try [Citadel](https://github.com/orlandos-nl/Citadel) for a higher-level wrapper.
