### ISSUE TITLE
Authentication Failed using Private Key,Public Key

### ISSUE THREAD

**Issue by ios-52** [apple/swift-nio-ssh#145]
Hello
We are trying to connect our Mac and aws servers using the private key. but every time we got authentication failed.
Also, we have checked both keys on another application and it's working fine.so I think the problem is in the library. can you please help?

using this method 
```
.byPublicKeyFromFile(username: self.username, password: "", publicKey: "", privateKey: pvtfilePath?.relativePath ?? "")
```
but not working can you please help us

**Comment by Lukasa** [comment]
Can you show me the complete code for how you configure your client?

**Comment by ios-52** [comment]
Here is my code.
Please help us
```
var session: NMSSHSession?
session = NMSSHSession(host: "192.168.0.228", port: Int(connection.port), andUsername: "Jigar D")
var pubfilePath = Bundle.main.url(forResource:"Jigarid_rsa", withExtension: "pub")
            var pvtfilePath = Bundle.main.url(forResource:"Jigarid_rsa", withExtension: "")
            session?.authenticate(byPublicKey: pubfilePath?.relativePath ?? "", privateKey: pvtfilePath?.relativePath ?? "", andPassword: "")
```

**Comment by Lukasa** [comment]
Without knowing the `NMSSHSession` code it's very hard to be more helpful. Is that code available anywhere?

**Comment by ios-52** [comment]
We are using this file please check
[Archive 3.zip](https://github.com/apple/swift-nio-ssh/files/11294470/Archive.3.zip)

**Comment by ios-52** [comment]
@Lukasa We already generate issue but not provide any solution.I think this library also used LibSSH2 because without that how can we connect server.

**Comment by Lukasa** [comment]
swift-nio-ssh does not use libssh2, it is a ground-up reimplementation of the SSH wire protocol.

**Comment by Lukasa** [comment]
NMSSHSession and swift-nio-ssh are entirely unrelated. swift-nio-ssh and libssh2 are entirely unrelated. I cannot support you with issues with libssh2.

**Comment by Lukasa** [comment]
Yes, swift-nio-ssh supports SSH private key authentication.

**Comment by Lukasa** [comment]
No, NMSSHSession and swift-nio-ssh are unrelated. You would use entirely different API calls.

**Comment by ios-52** [comment]
@Lukasa if possible can you please provide link or demo ?

**Comment by Lukasa** [comment]
There is an example [in this repository](https://github.com/apple/swift-nio-ssh/tree/main/Sources/NIOSSHClient). Alternatively, you could investigate [Citadel](https://github.com/orlandos-nl/Citadel).
