### ISSUE TITLE
ChannelError: operationUnsupported when executing commands from a daemon

### ISSUE THREAD

**Issue by eliaSchenker** [apple/swift-nio-ssh#166]
# Context
**NIO SSH Commit Hash**
```
36a4f6f4179ef5ebbeca501fc2125734b9f46290
```
**Swift version**
```
swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx14.0
```
**uname -a**
```
Darwin MacBook-Pro.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:55:06 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6020 arm64
```

Running Xcode 15.3 with macOS Sonoma 14.2.1 (23C71)

# Problem

When using nio-ssh to execute ssh commands in a daemonized context (built executable launched using launchctl with a config in `/Library/LaunchDaemons`) a ChannelError (`operationUnsupported`) is thrown.

I'm unsure if this is a problem just with nio-ssh or nio in general. Could it be that certain network operations aren't permitted from within a daemon?

Any information/help on this matter is greatly appreciated!

Forum post: https://forums.developer.apple.com/forums/thread/749910

# Reproduction

Reproduction can be found here: https://github.com/eliaSchenker/nio-ssh-daemon-issue/tree/main

To run the reproduction follow these steps:
- Build using Xcode (Product > Build)
- Find the executable in the build folder (Product > Show Build Folder in Finder)
- Move the executable to `/Library/PrivilegedHelperTools`
- Create a daemon configuration in `/Library/LaunchDaemons/nio-ssh-daemon.plist`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>Label</key>
		<string>nio-ssh-daemon</string>
		<key>ProgramArguments</key>
                 <array>
                 	<string>/Library/PrivilegedHelperTools/nio-ssh-daemon</string>
	    		<string>username:password@host</string>
			<string>ls -la</string>
                 </array>
		<key>KeepAlive</key>
		<true/>
		<key>ProcessType</key>
		<string>Interactive</string>
		<key>StandardOutPath</key>
		<string>/Library/Logs/nio-ssh-daemon.out.log</string>
		<key>StandardErrorPath</key>
		<string>/Library/Logs/nio-ssh-daemon.err.log</string>
	</dict>
</plist>
```
making sure to adjust the program arguments to include an host with username and password.
- Load the daemon using 
```
sudo launchctl load nio-ssh-daemon.plist
```
- When opening `Console.app`, navigating to `Log Reports` and opening `nio-ssh-daemon.out.log` the logged error will be shown:
```
Creating bootstrap
Connecting channel
Creating child channel
Waiting for connection to close
Error in pipeline: operationUnsupported
An error occurred: commandExecFailed
```

If the executable is run manually without a daemon it will work correctly:
```
./nio.ssh-daemon username:password@host
```

The reproduction is a copy of the example in the repository (https://github.com/apple/swift-nio-ssh/tree/main/Sources/NIOSSHClient) with slight modifications to log errors instead of using `try!`.

**Comment by eliaSchenker** [comment]
After some further debugging I found that the thrown error happens in `Bootstrap.swift` in the method `validateFileDescriptorIsNotAFile`. This method is called by `_takingOwnershipOfDescriptors` (same file). The input and output for the ownership are 0 and 1, the validation for the input passes, the one for the output fails at the following line:
```swift
  private func validateFileDescriptorIsNotAFile(_ descriptor: CInt) throws {
        // ...
        var s: stat = .init()
        try withUnsafeMutablePointer(to: &s) { ptr in
            try Posix.fstat(descriptor: descriptor, outStat: ptr)
        }
        switch s.st_mode & S_IFMT {
        case S_IFREG, S_IFDIR, S_IFLNK, S_IFBLK:
            throw ChannelError.operationUnsupported // Here the error occurrs
        default:
            () // Let's default to ok
        }
```

When running the application in the agent, the st_mode is `33188`,  when running it normally in Xcode, it is `8592`.

**Comment by Lukasa** [comment]
Thanks for doing that extra debugging. Yeah, `NIOPipeBootstrap` requires that FDs 0 and 1 are actually pipes, not files. It's not possible to do I/O to stdin and stdout this way in daemonized mode.

But that raises a question: where did you want your input and output to come from for a daemon? Presumably not stdin and stdout?

**Comment by eliaSchenker** [comment]
@Lukasa Thanks for your reply! Sorry I'm not really all that familiar with NIO or the nio-ssh library (hence the direct usage of the example). I wasn't aware that the example uses stdin/stdout in any way (the command is passed as a string, is the output of the sent command written to stdout?).

Ideally I would like to either write the result to a variable or ignore it alltogether. How would I adjust the example to do this instead of using stdin/stdout? If the error originates from the Bootstrap with input/output, do I have to initialize the channel with the bootstrap differently somehow?

**Comment by Lukasa** [comment]
The use of stdio is here: https://github.com/eliaSchenker/nio-ssh-daemon-issue/blob/4acb3aa7c8ab7bd314b48b2b8216df2ef21d0a2c/nio-ssh-daemon/ExecHandler.swift#L51

In your case, you don't need `GlueHandler` and you don't need the `NIOPipeBootstrap`. Instead, on `channelActive` you want to send your command in, and you can use `channelRead` to catch the returned data.

**Comment by eliaSchenker** [comment]
@Lukasa Thanks a lot, after removing the GlueHandler and Bootstrap, and sending command directly in channelActive it works inside of the daemon.

If anyone else experiences this in the future, I've adjusted the reproduction with the solution: https://github.com/eliaSchenker/nio-ssh-daemon-issue/tree/main
