### ISSUE TITLE
Error when adding swift-nio-ssh

### ISSUE THREAD

**Issue by zale-lee** [apple/swift-nio-ssh#168]
<img width="1239" alt="image" src="https://github.com/user-attachments/assets/b31add8e-0504-4d3b-a5f5-fc2cafedc310">

**Comment by Lukasa** [comment]
This looks like an error on your end: many versions of swift-crypto meet that version requirement. Can you reproduce this with a clean Package.swift in a new package?

**Comment by zale-lee** [comment]
<img width="1670" alt="image" src="https://github.com/user-attachments/assets/ecbc0712-3a38-4999-b47f-37194b9a83ec">
Just add this library and I get this error.

**Comment by zale-lee** [comment]
I deleted the project directory in ~/Library/Developer/Xcode/DerivedData and added it successfully。
Thank you。
