### ISSUE TITLE
NIOSSHClientServerAuthenticationDelegate failures appear to be unhandled

### ISSUE THREAD

**Issue by Dreksh** [apple/swift-nio-ssh#184]
Got a snippet of code where I believe the issue occurs:
https://github.com/apple/swift-nio-ssh/blob/5b4f9041e850e8b32e48f3a5b94ae6430a973616/Sources/NIOSSH/Key%20Exchange/SSHKeyExchangeStateMachine.swift#L316-L323

Context:
--------

I implemented my own NIOSSHClientServerAuthenticationDelegate: 
```
    struct ServerAuthValidator: NIOSSHClientServerAuthenticationDelegate {
        let knownHosts: Set<NIOSSHPublicKey>

        func validateHostKey(hostKey: NIOSSHPublicKey, validationCompletePromise: EventLoopPromise<Void>) {
            if self.knownHosts.contains(hostKey) {
                validationCompletePromise.succeed()
            } else {
                // TODO: How to terminate connection, this makes it hang instead
                validationCompletePromise.fail(Error.unknownServerKey)
            }
        }
    }
```
Where the knownHosts keys are a filtered version of the `.ssh/known_hosts` file based on the expected server's hostname I'm connecting to. However, on Ubuntu, the default behaviour of the known_hosts file has hashed the hostnames, resulting in my `knownHosts` variable to be an empty set. This solution for me in this case was to undo the hashing in Ubuntu https://askubuntu.com/questions/1393013/ssh-known-hosts-file-not-using-hostnames-anymore

With this setup where knownHosts is empty, no hosts will ever be valid, and the error case is propagated up to the promise. However, the connection did not terminate, instead it waited for more reads. Eventually hitting timeout that tore down the channel.

Request:
---------

I don't know what the expected behaviour is for the case where the client rejects all the public key validations (didn't read any RFCs). I would like the eventLoopFuture from the bootstrap's `connect` method to fail with some message relating to the cause.

**Comment by Dreksh** [comment]
Actually, it looks like the error is handled here:
https://github.com/apple/swift-nio-ssh/blob/5b4f9041e850e8b32e48f3a5b94ae6430a973616/Sources/NIOSSH/NIOSSHHandler.swift#L231-L247

Looks like it's up to the developer to catch this error event that's propagated back up.
But I'm surprised that the call to `ClientBootstrap(...).connect(..)` didn't throw when that promise failed, but instead kept waiting.

**Comment by Lukasa** [comment]
Thanks for filing this issue!

The promise from `ClientBootstrap.connect` only covers the case of the underlying TCP connection succeeding or failing. Generally if you want a different connection establishment promise, it's best to put that on another handler that you add in `channelInitializer` and have that handler expose something you can wait for.

**Comment by Dreksh** [comment]
Thanks for the explanation! Closing the issue
