### ISSUE TITLE
ssh -L

### ISSUE THREAD

**Issue by IdleJatt** [apple/swift-nio-ssh#59]
I am trying to use the codes from main.swift to do Local Port Forwarding but I am getting:: 
`bind(descriptor:ptr:bytes:): Operation not permitted (errno: 1)`

Can someone please help to do below SSH Cmd with Swift NIO SSH::
`ssh -L 4944:localhost:4944 root@__IP__ -p 5544`
**I sucessfully made a channel but not very sure what to do next for Port Forwarding**

I'm very new to Swift Nio, found it yesterday 😅

**Comment by Lukasa** [comment]
If you run the `NIOSSHClient` example, you should get exactly the same effect by running `swift run NIOSSHClient -L 4944:localhost:4944 root@__IP__:5544`. Assuming that works, can you clarify what the example is doing that is causing you confusion? It’ll make it easier to answer your questions.

**Comment by IdleJatt** [comment]
Thanks for quick response::
![image](https://user-images.githubusercontent.com/33171648/100977513-1aa72f80-3567-11eb-84f7-d24a0b14a7fd.png)

**Comment by Lukasa** [comment]
What platform is this? Are you deploying to iOS?

**Comment by IdleJatt** [comment]
> What platform is this? Are you deploying to iOS?

macos, its just a simple app with a Browser to open Google.com

**Comment by IdleJatt** [comment]
Ohh Really Sorry! I didn't enabled **Incoming Traffic** just enabled **Outgoing**
Really thankful to you! You saved me
