### ISSUE TITLE
Client remote port forwarding?

### ISSUE THREAD

**Issue by jurex** [apple/swift-nio-ssh#73]
Hey guys, is it possible to implement remote/reverse port forwarding from the client side? Something similar as `-R` switch used in the ssh command: `ssh -R 9090:localhost:8080 some.remoteserver.com`

I'm currently using swift-nio to run a local web server + websocket in the iOS application, and I would like to expose it using the remote ssh server without any additional port forwarding configured on the router. Is it something like this even possible using swift-nio? Thanks!

**Comment by Lukasa** [comment]
Yes, this supports reverse port forwarding using the [`forwardedTCPIP`](https://github.com/apple/swift-nio-ssh/blob/7ad2d6366d3338a95ddbd7026b99301f9df6c268/Sources/NIOSSH/Child%20Channels/SSHChannelType.swift#L36) channel type and the [`TCPForwardingRequest`](https://github.com/apple/swift-nio-ssh/blob/7ad2d6366d3338a95ddbd7026b99301f9df6c268/Sources/NIOSSH/GlobalRequestDelegate.swift#L41) global request.

There is currently no demo for this, so putting it together will require some fairly deep understanding of how SSH implements this functionality.

**Comment by jurex** [comment]
Awesome, thanks for quick reply! At least I know it's possible now, so I can start with basic experiments.
