### ISSUE TITLE
Channel closes after 1 command / Executing multiple requests on the same channel

### ISSUE THREAD

**Issue by hendesi** [apple/swift-nio-ssh#89]
Hi everybody,

first all of all, I want to say a huge thanks for extending SwiftNIO to support SSH connections and removing the need of relying on external libraries for ssh on swift.

I'm currently working on a ssh client that can execute requests on a remote machine. Since the project already relies on SwiftNIO, I was happy to hear about NIOSSH and wanted to use it for handling the connection and requests.
I oriented myself closely on the examples provided in [NIOSSHClient](https://github.com/apple/swift-nio-ssh/tree/main/Sources/NIOSSHClient) and initialised the channel and child channel like this:

```
let clientBootstrap = ClientBootstrap(group: group)
            .channelInitializer { channel in
                channel.pipeline.addHandlers([NIOSSHHandler(role: .client(.init(userAuthDelegate: InteractivePasswordPromptDelegate(username: self.username, password: self.password), serverAuthDelegate: AcceptAllKeysDelegate())), allocator: channel.allocator, inboundChildChannelInitializer: nil), ErrorHandler()])
            }
            .channelOption(ChannelOptions.socket(SocketOptionLevel(SOL_SOCKET), SO_REUSEADDR), value: 1)
            .channelOption(ChannelOptions.socket(SocketOptionLevel(IPPROTO_TCP), TCP_NODELAY), value: 1)
        
        self.channel = try clientBootstrap.connect(host: self.ipAdress, port: self.port).wait()
        
        let childChannel: Channel = try! channel!.pipeline.handler(type: NIOSSHHandler.self).flatMap { sshHandler in
            let promise = self.channel!.eventLoop.makePromise(of: Channel.self)
            sshHandler.createChannel(promise) { childChannel, channelType in
                guard channelType == .session else {
                    return self.channel!.eventLoop.makeFailedFuture(SSHClientError.invalidChannelType)
                }
                return childChannel.pipeline.addHandlers([ExecutionHandler(), ErrorHandler()])
            }
            return promise.futureResult
        }.wait()
        self.childChannel = childChannel
```

The `ExecutionHandler` that is passed to the childchannel's pipeline overrides `func triggerUserOutboundEvent` and triggers an internal outbound event that contains a `SSHChannelRequestEvent.ExecRequest` :

```
public func triggerUserOutboundEvent(context: ChannelHandlerContext, event: Any, promise: EventLoopPromise<Void>?) {
        guard let (buffer, responseHandler) = event as? (ByteBuffer, ((String, Int32) -> Void)?) else {
            promise?.fail(SSHError.invalidData)
            return
        }
        self.responseHandler = responseHandler
        let _ = context.triggerUserOutboundEvent(SSHChannelRequestEvent.ExecRequest(command: String(buffer: buffer), wantReply: false))
    }
```

This works fine for one request. But if i try to trigger multiple outbound events, i.e. send multiple `SSHChannelRequestEvent.ExecRequest`, it fails by returning `inputClosed` and the child channel is closed. This is problematic since it loses the state of the requests. If I wanted to change the directory with one request, the second one would start again in the root dir. 
I am fairly new to SwiftNIO and NIOSSH, so I wanted to ask if this is a known problem or am I just using the framework wrong? 
The `READ.me` states `...A session channel represents an invocation of a command.` Does this mean a `session` is supposed to be closed after one command? If so, is there still a possibility to maintain the state of a request? For now I've been concatenating related commands together with `command1 && command2` and executing them in one request. But this seems more like a hack to me.

Any help is greatly appreciated!

**Comment by Lukasa** [comment]
> The `READ.me` states `...A session channel represents an invocation of a command.` Does this mean a session is supposed to be closed after one command?

Yes. It seems like what you probably want is to request a shell instead, and then to send the commands you want to run as data within that shell session.

A way to think about this is that SSH considers "a shell" as just one kind of usage mode. The `ExecRequest` flow you're using is equivalent to the optional `command` arguments to the `ssh` binary, which lets you run a command directly on a remote machine as though you ran it locally (try `ssh <your host> hostname` and see what the result is). This allows only one command per child channel, and you'd need to open a new child channel to run another command.

In your case, you should probably be requesting a shell instead. Try [`ShellRequest`](https://github.com/apple/swift-nio-ssh/blob/bc1a91daf3ae35134fbca5655ed221668d0369d3/Sources/NIOSSH/Child%20Channels/ChildChannelUserEvents.swift#L113).

**Comment by hendesi** [comment]
@Lukasa 
Thanks for the quick response and clarifying about `ExecRequest`.
I've been already looking into `ShellRequest`, but wasn't quite able to get it to work. 
Do i use the first call of `triggerUserOutboundEvent` to send a `ShellRequest` and then in subsequent calls use `SSHChannelData` containing the actual request on the shell, or to what `data` are you referring to? I gave it a try and successfully send a shell request, but i could not send additional data through the channel. 

Unfortunately I wasn't able to find any example in the code containing `ShellRequest`, would you mind giving me a hint or example to learn/ work from?

**Comment by Lukasa** [comment]
Yes, sending `SSHChannelData` should be correct, that should be the equivalent of producing input on stdin.

Are you receiving any inbound user events or inbound data after you send your shell request?

**Comment by hendesi** [comment]
I created a [gist](https://gist.github.com/hendesi/b1fdaf1186a684db66e60a6800ca06f7)  that contains the relevant code.

After the first request I send a `ShellRequest` and receive a `NIOSSH.ChannelSuccessEvent()` on `channelRead` the linux shell initialisation text.  On the second request, I trigger a event containing the `SSHChannelData` with the request, but no inbound events or channel read events are received.

**Comment by Lukasa** [comment]
`SSHChannelData` is not sent in user events: you need to use `.write` and `.flush` to send it around.

**Comment by hendesi** [comment]
@Lukasa 
But when using
```
try client.childChannel?.triggerUserOutboundEvent(buffer).wait()
try client.childChannel?.write(buffer).wait()
``` 

and override `write` in `ExecutionHandler` like:
```
public func write(context: ChannelHandlerContext, data: NIOAny, promise: EventLoopPromise<Void>?) {
   let data = self.unwrapOutboundIn(data)
   context.writeAndFlush(self.wrapOutboundOut(SSHChannelData(type: .channel, data: .byteBuffer(data))), promise: promise)
}
```

I get the save result as above, i.e. no inbound/read events are received

**Comment by Lukasa** [comment]
Are you still sending the buffer in the outbound event?

Concretely, you need to send the ShellRequest and _then_, after you read the shell prompt, you can write your first command.

**Comment by hendesi** [comment]
> Are you still sending the buffer in the outbound event?

@Lukasa No, this was just an old code relict. This can be replaced by 
`try client.childChannel?.triggerUserOutboundEvent(SSHChannelRequestEvent.ShellRequest(wantReply: false)).wait()`.
But the result stays the same: I trigger the outbound event, i received the `NIOSSH.ChannelSuccessEvent()` inbound event. I call `childChannel.write` from the outside. And then the program is just kind of stuck..nothing, no inbound/read event, happens. 
Is there still anything wrong with the order of the requests?

**Comment by Lukasa** [comment]
Hmm, I can't reproduce the issue. Are you writing a full shell command _including the trailing newline_?

**Comment by hendesi** [comment]
Oh well, now this is embarrassing! **including the trailing newline**  fixes it for me 🎉 
Thanks a lot for your help!
