### ISSUE TITLE
Child channels can not access their own peerMaxMessageSize

### ISSUE THREAD

**Issue by gwynne** [apple/swift-nio-ssh#99]
There does not appear to be any way for a child channel implementation to get access to the `peerMaxMessageSize` value derived from the `SSH_MESSAGE_CHANNEL_OPEN` message. This value is needed by some subsystems, such as SFTP, which are required to manually perform splitting of large data packets manually. In SFTP's case, offering an oversized value in a WriteFile request causes some servers to enter a wedged state waiting for data that will never arrive; without access to the channel's desired maximum message size, it must assume the worst (the specification-required minimum supported size of 32768 payload bytes), which is obviously less than ideal.

**Comment by Lukasa** [comment]
Can you clarify the specific issue? swift-nio-ssh will manually fragment channel data messages: is there some reason to need to fragment beyond that?

If there is, the best thing to do is to add a new ChannelOption that can be used to retrieve the value.

**Comment by gwynne** [comment]
(P.S.: Yes, I did admit somewhere in the middle there that the max packet size value isn't so much "required" as it would improve efficiency 🤣. It'd also be pointless in the case of the specific server I described - the maximum packet size it specifies is exactly the SSH-required minimum value anyway 😅.)
